#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "Myddleware"
name = "Myddleware"
description.en = "Open Source connector"
description.fr = "connector Open Source"

version = "1.0.0~ynh1"
maintainers = []

[upstream]
license = "GPL-3.0-only"
website = "https://github.com/Myddleware/myddleware"
demo = "none"
admindoc = "https://myddleware.github.io/myddleware/#/"
code = "https://github.com/Myddleware/myddleware"

[integration]
yunohost = ">= 11.2.29"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/myddleware"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = [ "en_GB", "fr_FR", "it_IT"]
    default = "en_GB"
  
[resources]
    [resources.sources.main]
 SOURCE_URL="https://github.com/Myddleware/myddleware/archive/refs/tags/v4.0.2.tar.gz"
SOURCE_SUM="DJrmQ3oKJ7KsKjofX6gZbbz/O2dkiArzZp0i7Xpf028="
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "Myddleware-\\d+\\.\\d+\\.\\d+\\.tar\\.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "mariadb-server",
        "php-pear",
        "php8.3-ldap",
        "php8.3-mysql",
        "php8.3-cli",
        "php8.3-intl",
        "php8.3-zip",
        "php8.3-gd",
        "php8.3-mbstring",
        "php8.3-dom",
        "php8.3-curl",
    ]

    [resources.database]
    type = "mysql"
