#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# If fpm_footprint doesn't exist, create it
if [ -z "${fpm_footprint:-}" ]; then
    fpm_footprint=low
    ynh_app_setting_set --app=$app --key=fpm_footprint --value=$fpm_footprint
fi

# If fpm_free_footprint doesn't exist, create it
if [ -z "${fpm_free_footprint:-}" ]; then
    fpm_free_footprint=0
    ynh_app_setting_set --app=$app --key=fpm_free_footprint --value=$fpm_free_footprint
fi

# If fpm_usage doesn't exist, create it
if [ -z "${fpm_usage:-}" ]; then
    fpm_usage=low
    ynh_app_setting_set --app=$app --key=fpm_usage --value=$fpm_usage
fi

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# Get the current version of roundcube
oldversion=$(grep RCMAIL_VERSION "$install_dir/program/include/iniset.php" | cut -d\' -f4)

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=3

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir"
fi

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading PHP-FPM configuration..." --weight=5

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --usage=$fpm_usage --footprint=$fpm_footprint

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC UPGRADE
#=================================================
# CONFIGURE ROUNDCUBE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
    ynh_script_progression --message="Myddleware Roundcube..." --weight=1

    deskey=$(ynh_string_random --length=24)
    ynh_add_config --template="../conf/config.inc.php" --destination="$install_dir/config/config.inc.php"

    #=================================================
    # UPDATE DEPENDENCIES WITH COMPOSER
    #=================================================
    ynh_script_progression --message="Updating dependencies with Composer..." --weight=30

    # Upgrade composer itself
    ynh_install_composer

    # Check if dependencies need to be updated with Composer
    if [ -f "$install_dir/composer.json" ]
    then
        ynh_exec_warn_less ynh_composer_exec --commands="update"
        # Update plugin-installer for Composer version 2.0
        ynh_exec_warn_less ynh_composer_exec --commands="require roundcube/plugin-installer:>=0.2.0"
    else
        # Install composer.json
        cp "$install_dir/composer.json-dist" "$install_dir/composer.json"
    fi

    #=================================================
    # UPGRADE ADDITIONAL PLUGINS
    #=================================================
    ynh_script_progression --message="Upgrading additional plugins..." --weight=30

    # Create logs and temp directories
    mkdir -p "$install_dir/"{logs,temp}

    # Install net_LDAP
    ynh_composer_exec --commands="require kolab/net_ldap3"

    
    #=================================================
    # UPDATE Myddleware CONFIGURATION
    #=================================================
    ynh_script_progression --message="Updating $app configuration..." --weight=4

   

    # Update JavaScript dependencies
    pushd "$install_dir"
    COMPOSER_ALLOW_SUPERUSER=1 "php$phpversion" ./bin/update.sh --version="?" -y <<< ""

        # Store the config file checksum into the app settings
        ynh_store_file_checksum --file="$install_dir/config/config.inc.php"

        chmod 400 "$install_dir/config/config.inc.php"
        chown $app:$app "$install_dir/config/config.inc.php"

        #=================================================
        # UPDATE ROUNDCUBE CORE
        #=================================================
        ynh_script_progression --message="Updating $app core..." --weight=4

    COMPOSER_ALLOW_SUPERUSER=1 ynh_exec_warn "php$phpversion" ./bin/update.sh --version=$oldversion -y
    popd
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
